# Generated by Django 4.1.4 on 2023-01-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pub", "0002_alter_pub_log_id_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pub_log",
            name="after",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="pub_log",
            name="before",
            field=models.JSONField(null=True),
        ),
    ]
