# Generated by Django 4.1.4 on 2023-01-02 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sub", "0002_alter_sub_log_id_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pub", "0003_alter_pub_log_after_alter_pub_log_before"),
    ]

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=100)),
                ("field_change", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="pub_log",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="condition",
            name="log_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pub.pub_log"
            ),
        ),
    ]
