# Generated by Django 4.1.4 on 2023-01-03 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pub", "0004_condition_alter_post_user_alter_pub_log_id_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Condition_enum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pub.condition"
                    ),
                ),
            ],
        ),
    ]
