# Generated by Django 4.1.4 on 2023-01-03 04:06

from django.db import migrations, models
import django.db.models.deletion
import model_subscription.mixin


class Migration(migrations.Migration):

    dependencies = [
        ("pub", "0005_condition_enum"),
    ]

    operations = [
        migrations.CreateModel(
            name="log_change_condittion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_change", models.CharField(max_length=100)),
                ("before", models.JSONField(null=True)),
                ("after", models.JSONField(null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("check_change", models.BooleanField(default=True)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pub.condition"
                    ),
                ),
                (
                    "log_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pub.pub_log"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(model_subscription.mixin.SubscriptionModelMixin, models.Model),
        ),
    ]
