# Generated by Django 4.1.4 on 2023-01-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pub", "0009_mysubscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MySubscription",
        ),
    ]
