# Generated by Django 4.1.4 on 2023-01-05 06:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pub", "0012_remove_condition_enum_condition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feild", models.CharField(max_length=100)),
                ("condition", models.CharField(max_length=100)),
                ("value_change", models.CharField(max_length=100)),
                (
                    "next_condition",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("before", models.TextField()),
                ("after", models.TextField()),
                (
                    "conditions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("check_change", models.BooleanField(default=True)),
                (
                    "id_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pub.post"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
