# Generated by Django 4.1.4 on 2023-01-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pub", "0013_conditions_log"),
    ]

    operations = [
        migrations.DeleteModel(
            name="log",
        ),
    ]
