# Generated by Django 4.1.4 on 2023-01-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sub_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("before", models.TextField()),
                ("after", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("check_change", models.BooleanField(default=True)),
                (
                    "id_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pub.post"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pub.user"
                    ),
                ),
            ],
        ),
    ]
