# Generated by Django 4.1.4 on 2023-01-02 06:03

from django.db import migrations, models
import model_subscription.mixin


class Migration(migrations.Migration):

    dependencies = [
        ("sub", "0002_alter_sub_log_id_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=(model_subscription.mixin.SubscriptionModelMixin, models.Model),
        ),
    ]
